version: 2.1

jobs:
  test:
    docker:
    - image: golang:1.11.2
      environment:
        GO111MODULE: "on"
    steps:
    - checkout
    - restore_cache:
        name: Restore go modules cache
        keys:
        - mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "go.mod" }}
    - run:
        name: Install dependencies
        command: go mod download
    - run:
        name: Install linters
        command: |
          go get golang.org/x/tools/cmd/goimports
          go get golang.org/x/lint/golint
    - save_cache:
        name: Save go modules cache
        key: mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "go.mod" }}
        paths:
        - /go/pkg/mod/cache
    - run:
        name: Exec go vet
        command: go vet ./...
    - run:
        name: Exec goimports
        command: test -z "$(goimports -l . | tee /dev/stderr)"
    - run:
        name: Exec golint
        command: test -z "$(golint ./... | tee /dev/stderr)"
    - run:
        name: Run tests
        command: go test -v ./...

workflows:
  version: 2
  default:
    jobs:
    - test
