version: 2.1

jobs:
  test:
    docker:
    - image: golang:1.20.3
      environment:
        TEST_RESULTS: /tmp/test-results
    steps:
    - checkout
    - restore_cache:
        name: Restore go modules cache
        keys:
        - mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "go.mod" }}
    - run:
        name: Install dependencies
        command: go mod download
    - run:
        name: Install linters
        command: |
          go install golang.org/x/tools/cmd/goimports
          go install golang.org/x/lint/golint
          go install github.com/jstemmer/go-junit-report
    - save_cache:
        name: Save go modules cache
        key: mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "go.mod" }}
        paths:
        - /go/pkg/mod/cache
    - run:
        name: Exec go vet
        command: go vet ./...
    - run:
        name: Exec goimports
        command: test -z "$(goimports -l . | tee /dev/stderr)"
    - run:
        name: Exec golint
        command: test -z "$(golint ./... | tee /dev/stderr)"
    - run:
        name: Run tests
        command: |
          mkdir -p ${TEST_RESULTS}
          trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
          go test -coverprofile ${TEST_RESULTS}/coverage.txt -v ./... | tee ${TEST_RESULTS}/go-test.out
          go tool cover -html ${TEST_RESULTS}/coverage.txt -o ${TEST_RESULTS}/coverage.html
    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output
    - store_test_results:
        path: /tmp/test-results
  docker-build:
    docker:
    - image: circleci/python
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: build
        command: docker build --no-cache -t slacts:latest .
workflows:
  version: 2
  default:
    jobs:
    - test
    - docker-build
